application:
  name: tutorial
  project: postcodes
  organization: QoveryCommunity
databases:
- type: postgresql
  version: "12"
  name: my-postgresql
routers:
- name: main
  routes:
  - application_name: tutorial
    paths:
    - /
